language: generic
matrix:
  include:
  - script:
    - set -o pipefail
    - xcodebuild -scheme Base32 test | xcpretty
    - xcodebuild -scheme Base32 test -destination "name=iPhone 7" | xcpretty
    - xcodebuild -scheme Base32 test -destination "name=Apple TV 1080p" | xcpretty
    - xcodebuild -scheme Base32 build -destination "name=Apple Watch - 38mm" | xcpretty
    - swift test
    - pod lib lint
    env: JOB=macOS
    os: osx
    osx_image: xcode8.2
  - script: docker run -v `pwd`:`pwd` -w `pwd` norionomura/sourcekit:302 swift test
    env: JOB=Linux-Swift3.0.2
    sudo: required
    services: docker
  - script: docker run -v `pwd`:`pwd` -w `pwd` norionomura/sourcekit:3120170211a swift test
    env: JOB=Linux-Swift3.1
    sudo: required
    services: docker
notifications:
  webhooks:
    secure: TKFWG5dDRlNK/XbsC7eKDEh7vnydCUYjGc1Sv9DUOfRjvxYBMq+ys8R9iHAotNNtnCdacohM0bcwT1ZXQcRTYKEd6vKtY1XkkPA2xBogLVfhu17DCDMhJ3iTtati1mMK1rVeSgseXffOKVq1ZjNGjBVCIHl0PZoj5jFiOwYKKO8=
