aliases:
  - &steps-for-swiftpm
    - checkout
    - run: swift test

version: 2
jobs:
  linux_swift_4:
    docker:
      - image: norionomura/swift:40
    steps: *steps-for-swiftpm

  linux_swift_4.0.2:
    docker:
      - image: norionomura/swift:402
    steps: *steps-for-swiftpm

  linux_swift_4.0.3:
    docker:
      - image: norionomura/swift:403
    steps: *steps-for-swiftpm

  linux_swift_4.1:
    docker:
      - image: norionomura/swift:41
    steps: *steps-for-swiftpm

  linux_swift_4.1.1:
    docker:
      - image: norionomura/swift:411
    steps: *steps-for-swiftpm

  linux_swift_4.1.2:
    docker:
      - image: norionomura/swift:412
    steps: *steps-for-swiftpm

  linux_swift_4.1.3:
    docker:
      - image: norionomura/swift:413
    steps: *steps-for-swiftpm

  linux_swift_4.2:
    docker:
      - image: norionomura/swift:42
    steps: *steps-for-swiftpm

workflows:
  version: 2
  workflow:
    jobs:
      - linux_swift_4
      - linux_swift_4.0.2
      - linux_swift_4.0.3
      - linux_swift_4.1
      - linux_swift_4.1.1
      - linux_swift_4.1.2
      - linux_swift_4.1.3
      - linux_swift_4.2
