name: xcodebuild

on:
  push:
    branches: [master]
    paths: ['Sources/*', 'Tests/*', 'Base32.xcodeproj/*', '.github/workflows/xcodebuild.yml']
  pull_request:
    paths: ['Sources/*', 'Tests/*', 'Base32.xcodeproj/*', '.github/workflows/xcodebuild.yml']

jobs:
  xcodebuild:
    strategy:
      matrix:
        xcode:
          - version: '9.4.1'
          - version: '10'
            flag_for_test: -enableCodeCoverage YES -parallel-testing-enabled NO
          - version: '10.1'
            flag_for_test: -enableCodeCoverage YES -parallel-testing-enabled NO
          - version: '10.2'
            flag_for_test: -enableCodeCoverage YES -parallel-testing-enabled NO
          - version: '10.2.1'
            flag_for_test: -enableCodeCoverage YES -parallel-testing-enabled NO
          - version: '10.3'
            flag_for_test: -enableCodeCoverage YES -parallel-testing-enabled NO
          - version: '11'
            flag_for_test: -enableCodeCoverage YES -parallel-testing-enabled NO
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
      - run: xcodebuild -version
        env: 
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode.version }}.app
      - name: macOS
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode.version }}.app
        run: xcodebuild -scheme Base32 ${{ matrix.xcode.flag_for_test }} test | xcpretty
        shell: bash
      - name: iPhone Simulator
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode.version }}.app
        run: > 
          xcodebuild -scheme Base32 ${{ matrix.xcode.flag_for_test }} test
          -sdk iphonesimulator -destination "name=iPhone 8" | xcpretty
        shell: bash
      - name: Apple TV Simulator
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode.version }}.app
        run: >
          xcodebuild -scheme Base32 ${{ matrix.xcode.flag_for_test }} test
          -sdk appletvsimulator -destination "name=Apple TV 4K" | xcpretty
        shell: bash
      - name: watchOS Simulator
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode.version }}.app
        run: xcodebuild -scheme Base32 build -sdk watchsimulator | xcpretty
        shell: bash
      - run: curl -s https://codecov.io/bash | bash -s -- -t ${{ secrets.CODECOV_TOKEN }}
        shell: bash
